export const GET_POST_BY_LINK = 'GET_POST_BY_LINK';
export const GET_POST_BY_SUCCESS = 'GET_POST_BY_SUCCESS';
export const GET_POST_BY_ERROR = 'GET_POST_BY_ERROR';
export const HIDE_ALL_COUNTRIES = 'HIDE_ALL_COUNTRIES';
export const SHOW_ALL_COUNTRIES = 'SHOW_ALL_COUNTRIES';
export const LOAD_MORE_COUNTRIES = 'LOAD_MORE_COUNTRIES';




export const SEND_FINDING_TEXT = 'SEND_FINDING_TEXT';
export const FIND_COUNTRY_LINK = 'FIND_COUNTRY_LINK';
export const FIND_COUNTRY_SUCCESS = 'FIND_COUNTRY_SUCCESS';
export const FIND_COUNTRY_ERROR = 'FIND_COUNTRY_ERROR';

