export const GET_POST_BY_LINK = 'GET_POST_BY_LINK';
export const GET_POST_BY_SUCCESS = 'GET_POST_BY_SUCCESS';
export const GET_POST_BY_ERROR = 'GET_POST_BY_ERROR';
export const HIDE_ALL_COUNTRIES = 'HIDE_ALL_COUNTRIES';
export const SHOW_ALL_COUNTRIES = 'SHOW_ALL_COUNTRIES';
